#!/bin/sh
case "$1" in
  start)
    AS=$(cat /opt/etc/openvpn/invnet-autostart.conf 2>/dev/null | tr -d '[:space:]')
    if [ "$AS" = "yes" ]; then
      /opt/etc/init.d/S30invnet start
    fi
    ;;
  stop|status|restart) ;;
esac
