#!/bin/sh
PATH=/opt/bin:/opt/sbin:/sbin:/bin:/usr/sbin:/usr/bin
export PATH
printf "Content-Type: application/json; charset=utf-8\r\n\r\n"
( /opt/etc/init.d/S30vpn-aim stop >/opt/var/log/vpn-aim-action.log 2>&1 </dev/null & ) >/dev/null 2>&1
echo '{"ok":true,"status":"stopping"}'
