server.modules = ( "mod_cgi" )
server.document-root = "/opt/share/invnet"
server.port = 8888
server.bind = "0.0.0.0"
server.errorlog = "/opt/var/log/invnet-web.err"
server.pid-file = "/opt/var/run/invnet-web.pid"
index-file.names = ( "index.html" )

mimetype.assign = (
  ".html" => "text/html; charset=utf-8",
  ".js"   => "application/javascript",
  ".css"  => "text/css"
)

$HTTP["url"] =~ "^/cgi-bin/" {
  cgi.assign = ( "" => "/bin/sh" )
}
